name: ngly1-gpt

channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - plotly=5.15.0
  - jupyter=1.0.0
  - spacy=3.5.4
  - spacy-model-en_core_web_sm=3.5.0
  - pyarrow=12.0.1
  - python-dotenv=1.0.0
  - fire=0.5.0
  - networkx=3.1
  - plotnine=0.12.1
  - pygraphviz=1.11
  - pip: 
    - openai==0.27.8
    - pre-commit==3.3.3
