[tool.ruff]
target-version = "py310"
line-length = 120
ignore = [
    "E501",  # ignore line-length violations
]

[tool.mypy]
python_version = "3.10"
strict = true
pretty = true
show_error_context = true

[[tool.mypy.overrides]]
module = "yaml.*"
ignore_missing_imports = true
